/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TroubleTraceDetail struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	// 01:45:20
	AutoStopTime string `json:"AutoStopTime,omitempty"`
	// GUI
	Nodes string `json:"Nodes,omitempty"`
	// 75
	AutoStopRecords string `json:"AutoStopRecords,omitempty"`
	// 1
	TracePath string `json:"TracePath,omitempty"`
	// 1
	TraceConnections string `json:"TraceConnections,omitempty"`
	// 1
	TraceCache string `json:"TraceCache,omitempty"`
	// 1
	TraceData string `json:"TraceData,omitempty"`
	// 0
	ServerMonitor string `json:"ServerMonitor,omitempty"`
	// 1
	MonitoringFault string `json:"MonitoringFault,omitempty"`
	// string
	Purpose string `json:"Purpose,omitempty"`
	// Start
	TraceStatus string `json:"TraceStatus,omitempty"`
	FlightpathCombo *TroubleTraceDetailFlightpathCombo `json:"flightpathCombo,omitempty"`
	List []string `json:"List,omitempty"`
}
