/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RealConfigMonitoringOpt struct {
	// 1
	Id string `json:"id,omitempty"`
	// 200OK
	Name string `json:"name,omitempty"`
	// Check home page for 200 OK
	Description string `json:"description,omitempty"`
	// Check200
	Type_ string `json:"type,omitempty"`
	// /
	Url string `json:"url,omitempty"`
	Content string `json:"content,omitempty"`
	Username string `json:"Username,omitempty"`
	Password string `json:"Password,omitempty"`
	Threshold string `json:"Threshold,omitempty"`
	AppliedtoVS string `json:"AppliedtoVS,omitempty"`
}
