/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TroubleDownCapture struct {
	CaptureHidden string `json:"CaptureHidden,omitempty"`
	// eth0
	Adapter string `json:"Adapter,omitempty"`
	// 10
	Packets string `json:"Packets,omitempty"`
	// 4
	Duration string `json:"Duration,omitempty"`
	// CaptureAddress
	CaptureAddress string `json:"CaptureAddress,omitempty"`
}
