/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IpStatusWidget struct {
	IPStatusIP string `json:"IPStatus_IP,omitempty"`
	// 33,30,107,140,45,67,63,30,140,80,51,100
	IPStatusLayout string `json:"IPStatus_Layout,omitempty"`
	// status
	IPStatusName string `json:"IPStatus_Name,omitempty"`
	// IPStatus
	SectionName string `json:"Section_Name,omitempty"`
}
