/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SecurityEnableRest struct {
	// No SSL
	SCPRESTCertificate string `json:"SCP_RESTCertificate,omitempty"`
	// yes
	SCPRESTEnabled string `json:"SCP_RESTEnabled,omitempty"`
	// 192.168.1.184
	SCP_RESTIP string `json:"SCP_RESTIP,omitempty"`
	// 8087
	SCPRESTPort string `json:"SCP_RESTPort,omitempty"`
}
