/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateSysWidget struct {
	SystemName string `json:"System_Name,omitempty"`
	SystemType string `json:"System_Type,omitempty"`
	UpdateSectionName string `json:"Update_Section_Name,omitempty"`
}
