/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateRealRequestInner struct {
	// test
	Password string `json:"Password,omitempty"`
	// 23
	Threshold string `json:"Threshold,omitempty"`
	// test
	Username string `json:"Username,omitempty"`
	Content string `json:"content,omitempty"`
	// Check home page for 200 OK
	Description string `json:"description,omitempty"`
	// 1
	Id string `json:"id,omitempty"`
	// 200OK
	Name string `json:"name,omitempty"`
	// Check200
	Type_ string `json:"type,omitempty"`
	// /test/ab.aspx
	Url string `json:"url,omitempty"`
}
