/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SoftwareSaveLocationRespDetails struct {
	// true
	LOCATION string `json:"LOCATION,omitempty"`
	// true
	PUBLIC_IP_ADDRESS string `json:"PUBLIC_IP_ADDRESS,omitempty"`
}
