/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetupSetTime struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	NTPTimeZoneCombo *SetupSetTimeNtpTimeZoneCombo `json:"NTPTimeZoneCombo,omitempty"`
	NTPTypeCombo *SetupSetTimeNtpTypeCombo `json:"NTPTypeCombo,omitempty"`
	// 1
	Enabled string `json:"Enabled,omitempty"`
	// Asia/Calcutta
	NtpTimeZone string `json:"NtpTimeZone,omitempty"`
	// 0
	NTPType string `json:"NTPType,omitempty"`
	// 08/11/2014 07:53:11
	DateTime string `json:"DateTime,omitempty"`
	// www.server.com
	NtpTimeServer string `json:"NtpTimeServer,omitempty"`
	// 05:56
	NtpTimeUpdate string `json:"NtpTimeUpdate,omitempty"`
	// 24
	NtpPeriodUpdate string `json:"NtpPeriodUpdate,omitempty"`
}
