/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NotificationEmailEvent struct {
	CEEEvChannelAlertEnabled string `json:"CEEEvChannelAlertEnabled,omitempty"`
	CEEEvChannelAlertText string `json:"CEEEvChannelAlertText,omitempty"`
	CEEEvChannelNoticeEnabled string `json:"CEEEvChannelNoticeEnabled,omitempty"`
	CEEEvChannelNoticeText string `json:"CEEEvChannelNoticeText,omitempty"`
	CEEEvContentServerNoticeEnabled string `json:"CEEEvContentServerNoticeEnabled,omitempty"`
	CEEEvContentServerNoticeText string `json:"CEEEvContentServerNoticeText,omitempty"`
	CEEEvContentServerAlertEnabled string `json:"CEEEvContentServerAlertEnabled,omitempty"`
	CEEEvContentServerAlertText string `json:"CEEEvContentServerAlertText,omitempty"`
	CEEEvFlightPathEnabled string `json:"CEEEvFlightPathEnabled,omitempty"`
	CEEEvFlightPathText string `json:"CEEEvFlightPathText,omitempty"`
	CEEEvIpServiceAlertTextEnabled string `json:"CEEEvIpServiceAlertTextEnabled,omitempty"`
	CEEEvIpServiceAlertText string `json:"CEEEvIpServiceAlertText,omitempty"`
	CEEEvIpServiceNoticeEnabled string `json:"CEEEvIpServiceNoticeEnabled,omitempty"`
	CEEEvIpServiceNoticeText string `json:"CEEEvIpServiceNoticeText,omitempty"`
	CEEGroupEnabled string `json:"CEEGroupEnabled,omitempty"`
	CEEGroupText string `json:"CEEGroupText,omitempty"`
	CEEGroupTime string `json:"CEEGroupTime,omitempty"`
}
