/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DashdataOpt struct {
	// Event4
	PartID string `json:"PartID,omitempty"`
	// Event
	SectionName string `json:"SectionName,omitempty"`
	// event
	WidgetName string `json:"Widget_Name,omitempty"`
}
