/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateIpServiceWidget struct {
	IPServiceColumns string `json:"IPService_Columns,omitempty"`
	IPServiceName string `json:"IPService_Name,omitempty"`
	IPServicePeriod string `json:"IPService_Period,omitempty"`
	IPServiceType string `json:"IPService_Type,omitempty"`
	IPServiceVSRS string `json:"IPService_VSRS,omitempty"`
	UpdateSectionName string `json:"Update_Section_Name,omitempty"`
}
