/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type W3CLoggingListOpt struct {
	// 0
	Id string `json:"id,omitempty"`
	// w3c20140508-16.log
	Value string `json:"value,omitempty"`
}
