/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SecurityUpdateGui struct {
	// default
	SCPCertificateGUI3 string `json:"SCP_CertificateGUI3,omitempty"`
	// 1
	SCPChangeAccepted string `json:"SCP_ChangeAccepted,omitempty"`
	// 80
	SCPPortGUI3 string `json:"SCP_PortGUI3,omitempty"`
	// 443
	SCPSecurePortGUI3 string `json:"SCP_SecurePortGUI3,omitempty"`
}
