/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddOnsStop struct {
	// 870b59b6a541fbc7e365366a0751c0c987ca5447a933d011a670478b6bcd391c
	AddOnID string `json:"AddOnID,omitempty"`
	// 5
	ConfigID string `json:"ConfigID,omitempty"`
	// jetnexus/alb
	Repository string `json:"Repository,omitempty"`
}
