/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ValuesRow struct {
	// 0
	VId string `json:"vId,omitempty"`
	// $variable1$
	Variable string `json:"variable,omitempty"`
	// Query Item
	Source string `json:"source,omitempty"`
	// Charge-To
	Detail string `json:"detail,omitempty"`
	ValValue string `json:"valValue,omitempty"`
}
