/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobalSettingOpt struct {
	// openssl
	Id string `json:"id,omitempty"`
	// Open SSL
	Value string `json:"value,omitempty"`
}
