/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatusSaveRow struct {
	// 1
	Id string `json:"id,omitempty"`
	// 1
	LayoutCheck string `json:"layoutCheck,omitempty"`
	// 33
	Width string `json:"width,omitempty"`
}
