/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GlobSettingData struct {
	// true
	Success string `json:"success,omitempty"`
	// images/2light-hd.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	// openssl
	CryptoLib string `json:"CryptoLib,omitempty"`
	// 1
	HostCacheTimer string `json:"HostCacheTimer,omitempty"`
	GlobalSettingListString *GlobSettingDataGlobalSettingListString `json:"GlobalSettingListString,omitempty"`
	// 10
	LdapTimeout string `json:"LdapTimeout,omitempty"`
	// 0
	DrainClearPersistence string `json:"DrainClearPersistence,omitempty"`
}
