/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkData struct {
	// true
	Success string `json:"success,omitempty"`
	// images/2light-hd.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// Your changes have been applied
	StatusText string `json:"StatusText,omitempty"`
	SNATGrid *NetworkDataSnatGrid `json:"SNATGrid,omitempty"`
	Data *NetworkDataData `json:"data,omitempty"`
}
