/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtocolData struct {
	// true
	Success string `json:"success,omitempty"`
	// images/2light-hd.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	XFFCombo *ProtocolDataXffCombo `json:"XFFCombo,omitempty"`
	CompressAsYouGoCombo *ProtocolDataCompressAsYouGoCombo `json:"CompressAsYouGoCombo,omitempty"`
	// 0
	SendServerTooBusyPage string `json:"SendServerTooBusyPage,omitempty"`
	// 2
	XffOutputList string `json:"XffOutputList,omitempty"`
	// X-Forwarded-For t
	XffHeader string `json:"XffHeader,omitempty"`
	// 139
	CPF_INITIAL__PAGE_BUFFER_SIZE_K string `json:"CPF_INITIAL_ PAGE_BUFFER_SIZE_K,omitempty"`
	// 99990
	CPF_MAX_CONTENT_LENGTH_K string `json:"CPF_MAX_CONTENT_LENGTH_K,omitempty"`
	// 8
	CPF_INCREMENT_PAGE_BUFFER_SIZE_K string `json:"CPF_INCREMENT_PAGE_BUFFER_SIZE_K,omitempty"`
	// 207
	CPFMinimumCompressionSize string `json:"CPF_ MinimumCompressionSize,omitempty"`
	// 0
	CPF_DO_NOT_COMPRESS_CSS string `json:"CPF_DO_NOT_COMPRESS_CSS,omitempty"`
	// 1
	CPFCompressionDisabled string `json:"CPF_CompressionDisabled,omitempty"`
	// 1
	CPFCompressAsYouGo string `json:"CPF_CompressAsYouGo,omitempty"`
	// test exclusion for test t
	CurrentExclusions string `json:"CurrentExclusions,omitempty"`
	// Lax
	SameSite string `json:"SameSite,omitempty"`
	// 1
	Secure string `json:"Secure,omitempty"`
	// 0
	HttpOnly string `json:"HttpOnly,omitempty"`
	SameSiteListString *ProtocolDataSameSiteListString `json:"SameSiteListString,omitempty"`
}
