/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeleteCustomMonitorDelCsmComboOptionsOption struct {
	// Custom:customer/script0.pl
	Id string `json:"id,omitempty"`
	// test
	Value string `json:"value,omitempty"`
}
