/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CacheRulesRow struct {
	// 0
	Id string `json:"id,omitempty"`
	// New Rule
	Name string `json:"name,omitempty"`
	// New Rule Description
	Description string `json:"description,omitempty"`
	// +
	Add string `json:"add,omitempty"`
	CacheRuleText string `json:"cacheRuleText,omitempty"`
}
