/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StatusDataRow struct {
	// SubTotal
	RowType string `json:"RowType,omitempty"`
	// images/jnpsStateErrorIP.gif
	InterfaceImagePath string `json:"interfaceImagePath,omitempty"`
	// Real Servers unreachable
	InterfaceStatusReason string `json:"interfaceStatusReason,omitempty"`
	// images/jnpsStateErrorIP.gif
	ChannelImagePath string `json:"channelImagePath,omitempty"`
	// Real Servers unreachable
	ChannelStatusReason string `json:"channelStatusReason,omitempty"`
	ServiceName string `json:"serviceName,omitempty"`
	// 34.5.4.3:342
	VIPPort string `json:"VIPPort,omitempty"`
	// 0
	Hitsecnew string `json:"hitsecnew,omitempty"`
	// 0
	Cacheperc string `json:"cacheperc,omitempty"`
	// 0
	Compress string `json:"compress,omitempty"`
	// images/jnpsStateErrorIP.gif
	RsImagePath string `json:"rsImagePath,omitempty"`
	// Real Server unreachable
	RsStatusReason string `json:"rsStatusReason,omitempty"`
	// 23.4.3.23:342
	RealServer string `json:"realServer,omitempty"`
	RealServerNotes string `json:"realServerNotes,omitempty"`
	// 0
	Conn string `json:"conn,omitempty"`
	// 0
	Data string `json:"data,omitempty"`
	// 0
	Reqsec string `json:"reqsec,omitempty"`
	// 0
	SeriesDataConn string `json:"SeriesDataConn,omitempty"`
	// 0
	SeriesDataDat string `json:"SeriesDataDat,omitempty"`
	// 0
	SeriesDataReq string `json:"SeriesDataReq,omitempty"`
	// 0
	Pool string `json:"pool,omitempty"`
}
