/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClusMembersRow struct {
	// 1
	Id string `json:"id,omitempty"`
	// images/jnpsStateOnlineIP.gif
	Status string `json:"status,omitempty"`
	// Online
	ChannelStatusReason string `json:"channelStatusReason,omitempty"`
	// 192.168.1.188 ALB-X
	Clustermember string `json:"clustermember,omitempty"`
}
