/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DashIpStatusWidgetResp struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	// IPStatus4
	PartID string `json:"PartID,omitempty"`
	// 33,30,107,140,45,67,63,30,140,80,51,100,57,100,46,100,49
	IPStatusLayout string `json:"IPStatus_Layout,omitempty"`
	IPStatusIP string `json:"IPStatus_IP,omitempty"`
}
