/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SoftwareLocation struct {
	// AS45528 Tikona Digital Networks Pvt Ltd.
	As string `json:"as,omitempty"`
	// Noida
	City string `json:"city,omitempty"`
	// India
	Country string `json:"country,omitempty"`
	// IN
	CountryCode string `json:"countryCode,omitempty"`
	// Tikona Digital Networks Pvt. LTD
	Isp string `json:"isp,omitempty"`
	// 28.57
	Lat string `json:"lat,omitempty"`
	// 77.32
	Lon string `json:"lon,omitempty"`
	// Tikona Digital Networks Pvt
	Org string `json:"org,omitempty"`
	// 113.193.186.241
	Query string `json:"query,omitempty"`
	// UP
	Region string `json:"region,omitempty"`
	// Uttar Pradesh
	RegionName string `json:"regionName,omitempty"`
	// success
	Status string `json:"status,omitempty"`
	// Asia/Kolkata
	Timezone string `json:"timezone,omitempty"`
	// 201301
	Zip string `json:"zip,omitempty"`
}
