/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DashIpServiceWidgetResp struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	// IPService4
	PartID string `json:"PartID,omitempty"`
	// VS
	IPServiceType string `json:"IPService_Type,omitempty"`
	// 192.168.1.200:80
	IPServiceVSRS string `json:"IPService_VSRS,omitempty"`
	// day
	IPServicePeriod string `json:"IPService_Period,omitempty"`
	// Average Bytes in,Average Bytes out,Average Bytes cached
	IPServiceColumns string `json:"IPService_Columns,omitempty"`
}
