/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActionsRow struct {
	// 0
	AId string `json:"aId,omitempty"`
	Data string `json:"data,omitempty"`
	// Rewrite Path
	Action string `json:"action,omitempty"`
	// $path$l
	Target string `json:"target,omitempty"`
}
