/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LogClearListStringOpt struct {
	// 0
	Id string `json:"id,omitempty"`
	// System Logs (3 files)
	Value string `json:"value,omitempty"`
}
