/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FlightPathUpdateAct struct {
	// 1
	FId string `json:"fId,omitempty"`
	// 0
	AId string `json:"aId,omitempty"`
	// rewrite_path
	Action string `json:"action,omitempty"`
	// Pragma
	Target string `json:"target,omitempty"`
	Data string `json:"data,omitempty"`
}
