/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ManageCertificate struct {
	// true
	Success string `json:"success,omitempty"`
	// true
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	CertificateManageCombo *GetCertificateCertificateManageCombo `json:"CertificateManageCombo,omitempty"`
	ACECertificateListString *GetCertificateAceCertificateListString `json:"ACE_CertificateListString,omitempty"`
}
