/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AppData69Get struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif.
	StatusImage string `json:"StatusImage,omitempty"`
	// get.
	StatusText string `json:"StatusText,omitempty"`
	// admin.
	CsmKey string `json:"CsmKey,omitempty"`
	// 0800-2745-80BF.
	TimeofDay string `json:"TimeofDay,omitempty"`
}
