/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetCertificate struct {
	// true
	Success string `json:"success,omitempty"`
	// true
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText        string                           `json:"StatusText,omitempty"`
	CerKeyLenghtCombo *GetCertificateCerKeyLenghtCombo `json:"CerKeyLenghtCombo,omitempty"`
	CountryCombo      *GetCertificateCountryCombo      `json:"CountryCombo,omitempty"`
	//CertificateManageCombo *GetCertificateCertificateManageCombo `json:"CertificateManageCombo,omitempty"`
	ACECertificateListString *GetCertificateAceCertificateListString `json:"ACE_CertificateListString,omitempty"`
}
