/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetupUpdateServer struct {
	// www.server.com
	Timeserver string `json:"Timeserver,omitempty"`
	// 05|56
	Updated string `json:"Updated,omitempty"`
	// 24
	Updateperiod string `json:"Updateperiod,omitempty"`
	// Public SNTP v4
	NTPType string `json:"NTPType,omitempty"`
	// 0
	Enabled string `json:"Enabled,omitempty"`
}
