/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProtocolUpdate struct {
	// 2
	ForwardedForOutput string `json:"ForwardedForOutput,omitempty"`
	// X-Forwarded-For t
	ForwardedForHeader string `json:"ForwardedForHeader,omitempty"`
}
