/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CServerId struct {
	// 1.1.2
	ServerKey string `json:"serverKey,omitempty"`
	// 0
	CId string `json:"cId,omitempty"`
	// images/jnpsStateLicense.gif
	ImagePath string `json:"imagePath,omitempty"`
	// Licenced real servers exceeded
	StatusReason string `json:"statusReason,omitempty"`
	// 1
	CSActivity string `json:"CSActivity,omitempty"`
	// 192.168.1.21
	CSIPAddr string `json:"CSIPAddr,omitempty"`
	// 80
	CSPort string `json:"CSPort,omitempty"`
	CSNotes string `json:"CSNotes,omitempty"`
	// 100
	WeightFactor string `json:"WeightFactor,omitempty"`
	// 100
	WeightFactorCalculated string `json:"WeightFactorCalculated,omitempty"`
}
