/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RuleAuthentication struct {
	// 4
	AuthForm string `json:"AuthForm,omitempty"`
	// 3
	AuthServer string `json:"AuthServer,omitempty"`
	// forms
	ClientAuthMethod string `json:"ClientAuthMethod,omitempty"`
	// test
	Description string `json:"Description,omitempty"`
	// test
	Message string `json:"Message,omitempty"`
	// testRule1
	Name string `json:"Name,omitempty"`
	RootDomain string `json:"RootDomain,omitempty"`
	// ntlm
	ServerAuthMethod string `json:"ServerAuthMethod,omitempty"`
	// 56
	Timeout string `json:"Timeout,omitempty"`
}
