/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PowerPowerOff struct {
	// true
	Success string `json:"success,omitempty"`
	// true
	StatusImage string `json:"StatusImage,omitempty"`
	// Going to Power off jetNEXUS daemon or error message.
	StatusText string `json:"StatusText,omitempty"`
}
