/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FlightPathUpdate struct {
	// 1
	FId string `json:"fId,omitempty"`
	// new
	FlightPathName string `json:"flightPathName,omitempty"`
	// desc
	FlightPathDesc string `json:"flightPathDesc,omitempty"`
}
