/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RenewSslResponse struct {
	// true
	Success string `json:"success,omitempty"`
	// name
	CertificateName string `json:"CertificateName,omitempty"`
	// key
	Key string `json:"Key,omitempty"`
}
