/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LicenceDataData struct {
	// true
	Success string `json:"success,omitempty"`
	// jetNEXUS Evaluation Licence
	IssuedTo string `json:"IssuedTo,omitempty"`
	// sales@jetnexus.com
	ContactPerson string `json:"ContactPerson,omitempty"`
	// 26 Apr 2012
	DateIssued string `json:"DateIssued,omitempty"`
	// ALB-X VA
	ServerRef string `json:"ServerRef,omitempty"`
	// Not licenced - Please contact jetNEXUS Ltd quoting Machine ID 0800 - 271 B- E752 
	ALB string `json:"ALB,omitempty"`
	// Not licenced -Please contact jetNEXUS Ltd quoting Machine ID 0800 - 271 B - E752 
	SSL string `json:"SSL,omitempty"`
	// Not licenced -Please contact jetNEXUS Ltd quoting Machine ID 0800 - 271 B - E752 
	Cache string `json:"Cache,omitempty"`
	// Not licenced -Please contact jetNEXUS Ltd quoting Machine ID 0800- 271 B - E752 
	FlightPath string `json:"FlightPath,omitempty"`
	// Not licenced -Please contact jetNEXUS Ltd quoting Machine ID 0800- 271 B - E752 
	JetSTREAM string `json:"JetSTREAM,omitempty"`
	// Not licenced -Please contact jetNEXUS Ltd quoting Machine ID 0800- 271 B - E752 
	Interfaces string `json:"Interfaces,omitempty"`
	// Not licenced -Please contact jetNUS Ltdquoting Machine ID 0800- 271 B - E752 
	RealServers string `json:"RealServers,omitempty"`
	// 0800 - 271 B - E752 
	MachineID string `json:"MachineID,omitempty"`
	GLBLicense string `json:"GLBLicense,omitempty"`
	// Permanent licence 
	AuthLicense string `json:"AuthLicense,omitempty"`
	FirewallLicense string `json:"FirewallLicense,omitempty"`
	Throughput string `json:"Throughput,omitempty"`
	B2BLicense string `json:"B2BLicense,omitempty"`
	Layer4BaseLicense string `json:"Layer4BaseLicense,omitempty"`
	HttpBaseLicense string `json:"HttpBaseLicense,omitempty"`
	// 09 F5 - 1E0 A - FBB5 - AF03 
	ALB1 string `json:"ALB1,omitempty"`
	SSL1 string `json:"SSL1,omitempty"`
	Cache1 string `json:"Cache1,omitempty"`
	FlightPath1 string `json:"FlightPath1,omitempty"`
	JetSTREAM1 string `json:"JetSTREAM1,omitempty"`
	// 07 C0 - B978 - C942 - 8 AA8 
	Interfaces1 string `json:"Interfaces1,omitempty"`
	RealServers1 string `json:"RealServers1,omitempty"`
	// 0800 - 2745 - 80 BF 
	MachineID1 string `json:"MachineID1,omitempty"`
	GLBLicense1 string `json:"GLBLicense1,omitempty"`
	// 01 DD - 1 ABD - 9 FD1 - F446 
	AuthLicense1 string `json:"AuthLicense1,omitempty"`
	FirewallLicense1 string `json:"FirewallLicense1,omitempty"`
	Throughput1 string `json:"Throughput1,omitempty"`
	B2BLicense1 string `json:"B2BLicense1,omitempty"`
	Layer4BaseLicense1 string `json:"Layer4BaseLicense1,omitempty"`
	HttpBaseLicense1 string `json:"HttpBaseLicense1,omitempty"`
	// 5985 F176 - 0 DBF - 417 D - A62B - 614785505219 
	UUID string `json:"UUID,omitempty"`
}
