/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PreAuthRuleRow struct {
	// 1
	Id string `json:"id,omitempty"`
	// test1
	Name string `json:"Name,omitempty"`
	// t
	Description string `json:"Description,omitempty"`
	RootDomain string `json:"RootDomain,omitempty"`
	// new1
	AuthServer string `json:"AuthServer,omitempty"`
	// Basic(401)
	ClientAuthMethod string `json:"ClientAuthMethod,omitempty"`
	// BASIC
	ServerAuthMethod string `json:"ServerAuthMethod,omitempty"`
	// default
	AuthForm string `json:"AuthForm,omitempty"`
	// tr
	Message string `json:"Message,omitempty"`
	// 45
	Timeout string `json:"Timeout,omitempty"`
}
