/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PreAuthServerRow struct {
	// 1
	Id string `json:"id,omitempty"`
	// new1
	Name string `json:"Name,omitempty"`
	// test1
	Description string `json:"Description,omitempty"`
	// LDAP
	AuthMethod string `json:"AuthMethod,omitempty"`
	// local@test.com
	Domain string `json:"Domain,omitempty"`
	// 1.2.3.4
	Address string `json:"Address,omitempty"`
	// 34
	Port string `json:"Port,omitempty"`
	// test
	SearchBase string `json:"SearchBase,omitempty"`
	// Username and Domain
	LoginFormat string `json:"LoginFormat,omitempty"`
	// test
	Passphrase string `json:"Passphrase,omitempty"`
	// 45
	DeadTime string `json:"DeadTime,omitempty"`
	Searchcondition string `json:"Searchcondition,omitempty"`
}
