/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TroubleshootingData struct {
	// true
	Success string `json:"success,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// get
	StatusText string `json:"StatusText,omitempty"`
	CaptureAdapterCombo *TroubleshootingDataCaptureAdapterCombo `json:"CaptureAdapterCombo,omitempty"`
	// eth0
	CaptureAdapter string `json:"CaptureAdapter,omitempty"`
	// 99978
	CapturePackets string `json:"CapturePackets,omitempty"`
	// 5
	CaptureTime string `json:"CaptureTime,omitempty"`
	// 192.168.6.23
	CaptureAddress string `json:"CaptureAddress,omitempty"`
	// -1
	CaptureLeft string `json:"CaptureLeft,omitempty"`
	SupportFileCombo *TroubleshootingDataSupportFileCombo `json:"SupportFileCombo,omitempty"`
}
