/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LicenceFooterData struct {
	// true
	Success string `json:"success,omitempty"`
	// Copyright &copy; 2005-2017 edgeNEXUS Ltd. All Rights Reserved.
	StatusText string `json:"StatusText,omitempty"`
	// images/light-hd_red.gif
	StatusImage string `json:"StatusImage,omitempty"`
	// ALB-X
	PageTitle string `json:"PageTitle,omitempty"`
}
