/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkDataSnatGrid struct {
	ProtocolCombo *NetworkDataDataProtocolCombo `json:"ProtocolCombo,omitempty"`
	// 1
	Id string `json:"id,omitempty"`
	// 0
	Interface_ string `json:"interface,omitempty"`
	// 192.168.1.1
	Sourceip string `json:"sourceip,omitempty"`
	// 192.168.1.1
	Destinationip string `json:"destinationip,omitempty"`
	// all
	Protocol string `json:"protocol,omitempty"`
	// 80
	Sourceport string `json:"sourceport,omitempty"`
	// 80
	Destinationport string `json:"destinationport,omitempty"`
	// 192.168.1.1
	Snattoip string `json:"snattoip,omitempty"`
	// 80
	Snattoport string `json:"snattoport,omitempty"`
	// notes
	Notes string `json:"notes,omitempty"`
	// Error: Success
	Error_ string `json:"error,omitempty"`
}
