/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TroubleTrace struct {
	// 5000
	AutoStopRecords string `json:"AutoStopRecords,omitempty"`
	// 00|15|00
	AutoStopTime string `json:"AutoStopTime,omitempty"`
	// 1
	MonitoringFault string `json:"MonitoringFault,omitempty"`
	// All IPs
	Nodes string `json:"Nodes,omitempty"`
	// 1
	ServerMonitor string `json:"ServerMonitor,omitempty"`
	// true
	Start string `json:"Start,omitempty"`
	// 1
	TraceCache string `json:"TraceCache,omitempty"`
	// 0
	TraceConnections string `json:"TraceConnections,omitempty"`
	// 1
	TraceData string `json:"TraceData,omitempty"`
	// 1
	TracePath string `json:"TracePath,omitempty"`
}
