/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PowerCheckStatus struct {
	// true
	EnableJavaScriptLogging string `json:"EnableJavaScriptLogging,omitempty"`
	// images/2light-hd.gif
	PollTaskInterval string `json:"PollTaskInterval,omitempty"`
}
