/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateRemotesyslog struct {
	// 192.168.43.45
	RsysLog1IP string `json:"RsysLog1IP,omitempty"`
	// TCP
	RsysLog1PROTOCOL string `json:"RsysLog1PROTOCOL,omitempty"`
	// 192.168.43.48
	RsysLog2IP string `json:"RsysLog2IP,omitempty"`
	// UDP
	RsysLog2PROTOCOL string `json:"RsysLog2PROTOCOL,omitempty"`
	// 1
	RsysServer1enabled string `json:"RsysServer1enabled,omitempty"`
	// 1
	RsysServer2enabled string `json:"RsysServer2enabled,omitempty"`
	// 518
	RsysServerPort1 string `json:"RsysServerPort1,omitempty"`
	// 421
	RsysServerPort2 string `json:"RsysServerPort2,omitempty"`
}
