/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DetailsSslReq struct {
	// NewCertSign
	CetificateName string `json:"CetificateName,omitempty"`
	// ButtonFlag
	ButtonFlag string `json:"ButtonFlag,omitempty"`
	// PasteSignature
	PasteSignature string `json:"PasteSignature,omitempty"`
}
