/*
 * Edgenexus REST API
 *
 * EdgeADC REST Web Services User Guide
 *
 * API version: 4.2.3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SmartFilesOpt struct {
	// MyCSMTest.monitor.alb
	FileName string `json:"File_Name,omitempty"`
	// v2.1
	Version string `json:"Version,omitempty"`
	MessageDigest string `json:"Message_Digest,omitempty"`
	MachineId string `json:"Machine_Id,omitempty"`
	// PRODUCT1
	ProductId string `json:"Product_Id,omitempty"`
	// order1
	OrderId string `json:"Order_Id,omitempty"`
	// iVBORw0KGgo
	Icon string `json:"Icon,omitempty"`
	// Desc1
	Description string `json:"Description,omitempty"`
	// MyCSMTest
	Name string `json:"Name,omitempty"`
	// monitor.alb
	Type_ string `json:"Type,omitempty"`
	// iso13001
	Certified string `json:"Certified,omitempty"`
	// jetnexus
	Vendor string `json:"Vendor,omitempty"`
	// 21 oct
	ReleaseDate string `json:"ReleaseDate,omitempty"`
	DockerImageName string `json:"DockerImageName,omitempty"`
}
